### Term

- epoch : 1 forward and backward pass of ALL training samples
- batch_size : number of training samples in one forward & backwards pass
- number of iterations = number of passes, each pass using [batch)size] number of samples

e.g: 100 samples, batch_size=20 --> 100/20 = 5 iterations for 1 epoch

In [3]:
import torch
import torchvision
from torch.utils.data import Dataset, DataLoader
import numpy as np
import math

In [29]:
class WineDataset(Dataset):
    def __init__(self):
        xy = np.loadtxt("wine.csv", delimiter="," , dtype=np.float32 , skiprows=1)
        self.x = torch.from_numpy(xy[:, 1:])
        self.y = torch.from_numpy(xy[: , [0]])
        self.n_samples = xy.shape[0]
                 
    def __getitem__(self, index):
        return self.x[index] , self.y[index]
                 
    def __len__(self):
        return self.n_samples
                 

In [30]:
dataset = WineDataset()

In [31]:
first_data =  dataset[0]

In [32]:
features, labels = first_data

In [33]:
features

tensor([1.4230e+01, 1.7100e+00, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00,
        3.0600e+00, 2.8000e-01, 2.2900e+00, 5.6400e+00, 1.0400e+00, 3.9200e+00,
        1.0650e+03])

In [34]:
dataset[:10]

(tensor([[1.4230e+01, 1.7100e+00, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00,
          3.0600e+00, 2.8000e-01, 2.2900e+00, 5.6400e+00, 1.0400e+00, 3.9200e+00,
          1.0650e+03],
         [1.3200e+01, 1.7800e+00, 2.1400e+00, 1.1200e+01, 1.0000e+02, 2.6500e+00,
          2.7600e+00, 2.6000e-01, 1.2800e+00, 4.3800e+00, 1.0500e+00, 3.4000e+00,
          1.0500e+03],
         [1.3160e+01, 2.3600e+00, 2.6700e+00, 1.8600e+01, 1.0100e+02, 2.8000e+00,
          3.2400e+00, 3.0000e-01, 2.8100e+00, 5.6800e+00, 1.0300e+00, 3.1700e+00,
          1.1850e+03],
         [1.4370e+01, 1.9500e+00, 2.5000e+00, 1.6800e+01, 1.1300e+02, 3.8500e+00,
          3.4900e+00, 2.4000e-01, 2.1800e+00, 7.8000e+00, 8.6000e-01, 3.4500e+00,
          1.4800e+03],
         [1.3240e+01, 2.5900e+00, 2.8700e+00, 2.1000e+01, 1.1800e+02, 2.8000e+00,
          2.6900e+00, 3.9000e-01, 1.8200e+00, 4.3200e+00, 1.0400e+00, 2.9300e+00,
          7.3500e+02],
         [1.4200e+01, 1.7600e+00, 2.4500e+00, 1.5200e+01, 1.1200e

In [51]:
dataloader = DataLoader(dataset=dataset, batch_size = 8, shuffle=True,)

In [58]:
dataiter = iter(dataloader)

data = next(dataiter)

features, labels = data

features, labels

(tensor([[1.3050e+01, 1.6500e+00, 2.5500e+00, 1.8000e+01, 9.8000e+01, 2.4500e+00,
          2.4300e+00, 2.9000e-01, 1.4400e+00, 4.2500e+00, 1.1200e+00, 2.5100e+00,
          1.1050e+03],
         [1.2520e+01, 2.4300e+00, 2.1700e+00, 2.1000e+01, 8.8000e+01, 2.5500e+00,
          2.2700e+00, 2.6000e-01, 1.2200e+00, 2.0000e+00, 9.0000e-01, 2.7800e+00,
          3.2500e+02],
         [1.3240e+01, 3.9800e+00, 2.2900e+00, 1.7500e+01, 1.0300e+02, 2.6400e+00,
          2.6300e+00, 3.2000e-01, 1.6600e+00, 4.3600e+00, 8.2000e-01, 3.0000e+00,
          6.8000e+02],
         [1.2370e+01, 1.0700e+00, 2.1000e+00, 1.8500e+01, 8.8000e+01, 3.5200e+00,
          3.7500e+00, 2.4000e-01, 1.9500e+00, 4.5000e+00, 1.0400e+00, 2.7700e+00,
          6.6000e+02],
         [1.3580e+01, 1.6600e+00, 2.3600e+00, 1.9100e+01, 1.0600e+02, 2.8600e+00,
          3.1900e+00, 2.2000e-01, 1.9500e+00, 6.9000e+00, 1.0900e+00, 2.8800e+00,
          1.5150e+03],
         [1.4160e+01, 2.5100e+00, 2.4800e+00, 2.0000e+01, 9.1000e

In [59]:
## training loop
batch_size = 8
total_samples = len(dataset)
n_iterations = math.ceil(total_samples/batch_size)
num_epochs = 1
total_samples, n_iterations

(178, 23)

In [60]:
for epoch in range(num_epochs):
    for i, (inputs, labels) in enumerate(dataloader):
         if (i+1) % 5 == 0:
            print(f'Epoch: {epoch+1}/{num_epochs}, Step {i+1}/{n_iterations}| Inputs {inputs.shape} | Labels {labels.shape}')

Epoch: 1/1, Step 5/23| Inputs torch.Size([8, 13]) | Labels torch.Size([8, 1])
Epoch: 1/1, Step 10/23| Inputs torch.Size([8, 13]) | Labels torch.Size([8, 1])
Epoch: 1/1, Step 15/23| Inputs torch.Size([8, 13]) | Labels torch.Size([8, 1])
Epoch: 1/1, Step 20/23| Inputs torch.Size([8, 13]) | Labels torch.Size([8, 1])
